// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
	"time"

	"github.com/ohhfishal/resume-wizard/resume"
)

type ApplicationHistory struct {
	ID          int64          `json:"id"`
	UserID      int64          `json:"user_id"`
	ResumeID    int64          `json:"resume_id"`
	Status      string         `json:"status"`
	Company     string         `json:"company"`
	Position    string         `json:"position"`
	Description sql.NullString `json:"description"`
	CreatedAt   time.Time      `json:"created_at"`
}

type Resume struct {
	ID        int64         `json:"id"`
	UserID    int64         `json:"user_id"`
	Name      string        `json:"name"`
	Resume    resume.Resume `json:"resume"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	LastUsed  sql.NullTime  `json:"last_used"`
	DeletedAt sql.NullTime  `json:"deleted_at"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}
