// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/ohhfishal/resume-wizard/resume"
)

type Resume struct {
	Name string         `json:"name"`
	Body *resume.Resume `json:"body"`
}
